### PR TITLE
Implements XrmUiTest.Navigation.clickCommand

### PR DESCRIPTION
**Pull request by camelCaseDave**

### CODE REVIEW

**Comment by DigitalFlow** [comment]
Hi @camelCaseDave,

thanks for this PR, I'm really grateful for your contributions 👍 

But is it possible, that this functionality is already covered by XrmUiTest.Button.press?
Can you check whether this fulfills your need as well?

Kind Regards,
Florian

**Comment by camelCaseDave** [comment]
Hey @DigitalFlow 

Oh I didn't see that function, I'll take a look.

**Comment by DigitalFlow** [comment]
@camelCaseDave:

No problem.
I'm still working on the IntelliSense documentation, some functions already have it.
Do you think we need a public HTML documentation of available functions? I think I might add one quite soon.

**Comment by camelCaseDave** [comment]
@DigitalFlow like in the README or a Wiki? Then yeah I think so.

I just wrote a blog about your repo: https://daveclark.io/ So I'm hoping a few more people will start using it and contributing!

**Comment by DigitalFlow** [comment]
@camelCaseDave:
I have just read that article, it's awesome, even with videos! 👍 
Really props to you and thank you very much for writing it. 

I'll create an API documentation very soon, hopefully it's easier to get an overview then.
Might add tutorials to it as well.

**Pull request closed without merging**
